image: node:18

stages:
  - api-test
  - deploy

variables:
  REPORT_DIR: reports


# =====================
# API TEST JOB
# =====================

api_tests:

  stage: api-test

  before_script:

    - apt-get update
    - apt-get install -y openjdk-17-jre

    - java -version

    - npm install -g newman
    - npm install -g newman-reporter-htmlextra
    - npm install -g newman-reporter-allure

    - npm install -g allure-commandline

    - mkdir -p $REPORT_DIR
    - mkdir -p allure-results
    - mkdir -p public

  script:

    - echo "Running Newman Tests..."

    - newman run tests/bookstore.postman_collection.json \
        -e tests/qa.postman_environment.json \
        --reporters cli,htmlextra,junit,allure \
        --reporter-htmlextra-export $REPORT_DIR/newman-report.html \
        --reporter-junit-export $REPORT_DIR/junit-report.xml \
        --reporter-allure-export allure-results || true

    - echo "Check Allure Results"
    - ls -la allure-results || true

    - echo "Generate Allure Dashboard"

    - allure generate allure-results --clean -o public || true

    - echo "Verify Public Folder"
    - ls -la public || true

  artifacts:

    when: always

    expire_in: 1 week

    paths:
      - public
      - reports/

    reports:
      junit:
        - reports/junit-report.xml


# =====================
# PAGES DEPLOYMENT
# =====================

pages:

  stage: deploy

  script:
    - echo "Deploying GitLab Pages"

  artifacts:
    paths:
      - public

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'