image: node:18

stages:
  - deploy

pages:
  stage: deploy

  before_script:

    - npm install -g newman
    - npm install -g newman-reporter-htmlextra
    - npm install -g newman-reporter-junitfull

    # create folders
    - mkdir -p public
    - mkdir -p reports

  script:

    - echo "Running Newman..."

    - newman run tests/bookstore.postman_collection.json \
        -e tests/qa.postman_environment.json \
        --reporters cli,htmlextra,junitfull \
        --reporter-htmlextra-export public/index.html \
        --reporter-junitfull-export reports/junit-report.xml

    - echo "Verify generated files"

    - ls -la public || true
    - ls -la reports || true

    # IMPORTANT — avoid job failure if junit missing
    - test -f reports/junit-report.xml || echo "JUnit report missing"

  artifacts:

    when: always

    paths:
      - public
      - reports

    # SAFE junit upload
    reports:
      junit:
        - reports/*.xml

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'